### ISSUE TITLE
How to use the trained model

### ISSUE THREAD

**Issue by michael2221807** [thaoshibe/BeautyGAN-PyTorch-reimplementation#1]
Hi, I used your code to train a new model, however, I don't know how should I use it to generate fake images. Thanks a lot for helping.

**Comment by michael2221807** [comment]
Sorry about the previous issue. On Tensorboard, all I got are some masked images instead of the coloured images. I am not sure what I did wrong. Thanks for helping:)
![0_499_fake](https://user-images.githubusercontent.com/16907073/114657646-17952a80-9d23-11eb-8f74-cd1dfe5a5809.jpg)
Something like this instead of the one you showed in your instruction.

**Comment by thaoshibe** [comment]
Hello. Could you provide more details?

**Comment by michael2221807** [comment]
I used the train.py provided to train and I see the Tensorboard output images to be all mask images. I wonder if anything I did wrong, bc I am new to the machine learning staff:) THX for replying！
![2a6e8fd724a816d813eb03a7d857868](https://user-images.githubusercontent.com/16907073/114706167-3c0cf900-9d5b-11eb-87cd-12082c2ab77b.png)

**Comment by michael2221807** [comment]
Also, I used the test.py provided by the original author to generate output by the trained model and the outputs are also masked images.

**Comment by michael2221807** [comment]
Sorry for the bother. I have resolved the issue, this is due to the difference between Linux and Windows file paths. I changed the / to \\ in the makeup data loader and now images file can successfully be read.
![0381d99125c5e4ef694bab4963eaa29](https://user-images.githubusercontent.com/16907073/114807734-8339cf00-9dd9-11eb-87ce-63ee718b69ac.png)
