### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by 962673247** [thaoshibe/BeautyGAN-PyTorch-reimplementation#10]
因为源数据集已经不可用，我在网上找到了数据集但是可能里面的文件和元数据及不太一样，能否提供源数据集的文件夹结构？

**Comment by thaoshibe** [comment]
Hi, I am not the author of BeautyGAN, so I do not process the MT dataset. Please refer to https://github.com/VinAIResearch/CPM/issues/11#issuecomment-912403455 for further information.

For my downloaded dataset, I used to have it in my personal computer. Unfortunately, I changed my laptop recently.
About the Google Drive, I also deleted it to save my personal storage :( I'm sorry.
You might email the author of BeautyGAN and ask for it!
