### ISSUE TITLE
 A question

### ISSUE THREAD

**Issue by XYFFFFFF** [thaoshibe/BeautyGAN-PyTorch-reimplementation#3]
Excuse, what is the difference between the setting of args.model == 'cycleGAN' and args.model =='makeupGAN'

**Comment by thaoshibe** [comment]
Hello there, sorry for the late reply.

`cycleGAN` is basically only CycleGAN. `makeupGAN` is CycleGAN + [Makeup Loss](https://github.com/thaoshibe/BeautyGAN-PyTorch-reimplementation/blob/ea34b6b444b990a0465fdc54f695e4ffcfdb47b4/solver_makeup.py#L367).
