### ISSUE TITLE
the test code

### ISSUE THREAD

**Issue by Yueming6568** [thaoshibe/BeautyGAN-PyTorch-reimplementation#5]
Hello, do you have a plan to release the testing code?

**Comment by thaoshibe** [comment]
Hello there,
I don't have any plan to maintain this repo anymore. But for the test code, you can check [test.py](https://github.com/wtjiang98/BeautyGAN_pytorch/blob/master/test.py).

**Comment by Yueming6568** [comment]
Hello thaoshibe,
Thank you for your apply！I will check it : )
