### ISSUE TITLE
Advice for segmentation

### ISSUE THREAD

**Issue by BobaBobek** [thaoshibe/BeautyGAN-PyTorch-reimplementation#8]
Hi,
I have different makeup image database (non-makup + makup images), but  there is no segmentation. Could you please advice me how to prepare segmented images? Is there any library?
Thanks

**Comment by thaoshibe** [comment]
Hello there,
To get facial segmentation, I used [[face-parsing.Pytorch](https://github.com/zllrunning/face-parsing.PyTorch)]. (There are lots of facial segmentation models out there. face-parsing.Pytorch is just my personal recommendation).

<img src="https://user-images.githubusercontent.com/22058807/119296332-f2310000-bc82-11eb-8b16-fd22c8cc8912.png" alt="facial-segmentation" width="100"/>

_(Face-parsing will give you facial attributes such as upper lip, lower lip, left eye, right eye, hair, etc. Check [here ](https://github.com/zllrunning/face-parsing.PyTorch/blob/d2e684cf1588b46145635e8fe7bcc29544e5537e/prepropess_data.py#L17)for details)_

Hope this helps!

**Comment by BobaBobek** [comment]
Great, thanks lot!

**Comment by thaoshibe** [comment]
Sure! Feel free to discuss if you have any other trouble! I'm happy to help!
